USE [TESTDB]
GO

-- 야근 히스토리
CREATE TABLE [dbo].[OVERTIME_WORK_LOG](
	[USER_ID] [varchar](6) NOT NULL,
	[FR_DTS] [datetime2](0) NOT NULL,
	[TO_DTS] [datetime2](0) NOT NULL,
	[RSN] [varchar](100) NOT NULL,
	[GEN_TIME] [int] NOT NULL,
	[REG_DTS] [datetime2](0) NOT NULL,
 CONSTRAINT [PK_OVERTIME_WORK_LOG] PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC,
	[FR_DTS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
GO
-- 대휴 히스토리
CREATE TABLE [dbo].[TIME_OFF_LOG](
	[USER_ID] [varchar](6) NOT NULL,
	[FR_DTS] [datetime2](0) NOT NULL,
	[TO_DTS] [datetime2](0) NOT NULL,
	[USE_TIME] [int] NOT NULL,
	[REG_DTS] [datetime2](0) NOT NULL,
 CONSTRAINT [PK_TIME_OFF_LOG] PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC,
	[FR_DTS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

GO
-- 야근 등록 프로시저
CREATE PROC [dbo].[USP_INSERT_OVERTIME_WORK_LOG]
(
    @USER_ID VARCHAR(6) = '',
	@FR_DT VARCHAR(20) = '',
	@TO_DT VARCHAR(20) = '',
	@RSN   VARCHAR(100) = ''
)
AS
INSERT INTO dbo.OVERTIME_WORK_LOG 
(
  USER_ID
, FR_DTS
, TO_DTS
, RSN
, GEN_TIME
, REG_DTS
)
VALUES(
 @USER_ID
,CONVERT(DATETIME,@FR_DT,120)
,CONVERT(DATETIME,@TO_DT,120)
,@RSN
,DATEDIFF(MINUTE,CONVERT(DATETIME,@FR_DT,120),CONVERT(DATETIME,@TO_DT,120))
,GETDATE()
);
GO
-- 대휴 등록 프로시저
CREATE PROC [dbo].[USP_INSERT_TIME_OFF_LOG]
(
    @USER_ID VARCHAR(6) = '',
	@FR_DT VARCHAR(20) = '',
	@TO_DT VARCHAR(20) = ''
)
AS
INSERT INTO dbo.TIME_OFF_LOG 
(
  USER_ID
, FR_DTS
, TO_DTS
, USE_TIME
, REG_DTS
)
VALUES(
 @USER_ID
,CONVERT(DATETIME,@FR_DT,120)
,CONVERT(DATETIME,@TO_DT,120)
,DATEDIFF(MINUTE,CONVERT(DATETIME,@FR_DT,120),CONVERT(DATETIME,@TO_DT,120))
,GETDATE()
);
GO
-- 야근 등록 조회
CREATE PROC [dbo].[USPS_SELECT_OVERTIME_WORK_LOG]
(
    @USER_ID VARCHAR(6) = ''
)
AS
SELECT USER_ID
, CONVERT(VARCHAR,FR_DTS) AS FR_DTS
, CONVERT(VARCHAR,TO_DTS) AS TO_DTS
, RSN
, GEN_TIME
, CONVERT(VARCHAR,REG_DTS) AS REG_DTS
FROM OVERTIME_WORK_LOG
WHERE USER_ID = @USER_ID 

GO
-- 대휴 등록 조회
CREATE PROC [dbo].[USPS_SELECT_TIME_OFF_LOG]
(
    @USER_ID VARCHAR(6) = ''
)
AS
SELECT 
  USER_ID
, CONVERT(VARCHAR,FR_DTS) AS FR_DTS
, CONVERT(VARCHAR,TO_DTS) AS TO_DTS
, USE_TIME
, CONVERT(VARCHAR,REG_DTS) AS REG_DTS
FROM TIME_OFF_LOG
WHERE USER_ID = @USER_ID

GO

-- 남은 대휴 시간 조회
CREATE PROC [dbo].[USPS_SELECT_SPARE_TIME_OFF]
( @USER_ID VARCHAR(6) = '' )
AS

DECLARE @WORK_SUM BIGINT
DECLARE @OFF_SUM BIGINT

SELECT @WORK_SUM = ISNULL(SUM(GEN_TIME),0)
FROM OVERTIME_WORK_LOG
WHERE USER_ID = @USER_ID

SELECT @OFF_SUM = ISNULL(SUM(USE_TIME),0)
FROM TIME_OFF_LOG
WHERE USER_ID = @USER_ID

SELECT @USER_ID AS USER_ID
, @WORK_SUM - @OFF_SUM AS SPARE_MINUTE
, (@WORK_SUM - @OFF_SUM)/60. AS SPARE_HOUR

